# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_weeks', models.IntegerField(default=0)),
                ('instructor', models.CharField(max_length=200)),
                ('taught_via', models.CharField(max_length=200)),
                ('starts_by', models.DateField()),
                ('obsolete', models.BooleanField(default=False)),
                ('class_length', models.CharField(max_length=200)),
                ('submit_as', models.CharField(max_length=200)),
            ],
        ),
    ]
