# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20160320_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='taught_via',
        ),
    ]
