# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 22:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_class_taught_via'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name', 'obsolete'], 'verbose_name_plural': 'classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_length',
        ),
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 4500)),
        ),
    ]
