# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_workshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={},
        ),
        migrations.RemoveField(
            model_name='class',
            name='obsolete',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='obsolete',
        ),
    ]
