# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 02:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0008_auto_20160326_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_weeks', models.IntegerField(default=0)),
                ('starts_by', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(0, 4500))),
                ('broadcast_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.BroadcastPlatform')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='school.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='broadcast_platform',
        ),
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
